name: Publish Mod

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.7
  JAVA_VERSION: 21
  MOD_VERSION: 1.1.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build
        run: bash ./gradlew :${{ env.MINECRAFT_VERSION }}:buildAndCollect

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          tag_name: "${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          name: "${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          files: build/libs/${{ env.MOD_VERSION }}/*.jar

      - name: Publish ${{ env.MINECRAFT_VERSION }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.M_TOKEN }}
          files: build/libs/${{ env.MOD_VERSION }}/one-click-anvil-${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}*.jar
          name: "${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          version-type: release
          loaders: fabric
          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"
          dependencies: |
            fabric-api
            modmenu
            yacl
